#
# http://travis-ci.org configuration file for openMVG
#

language: cpp

compiler:
  - gcc
  #- clang: #Consider clang later, since cereal does not build fine on the clang CI version
  #  - "3.3"

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - lcov
      - libpng-dev
      - libjpeg8-dev
      - libtiff4-dev
      - libxxf86vm1
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - libxrandr-dev
      - g++-4.8

env:
  global:
    - NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU
    - OPENMVG_SOURCE=${TRAVIS_BUILD_DIR}/src
    - OPENMVG_BUILD=${TRAVIS_BUILD_DIR}/build

before_install:
 - gem install coveralls-lcov

before_script:
  - export CXX="g++-4.8"
  # Create build folder
  - mkdir $OPENMVG_BUILD
  - cd $OPENMVG_BUILD
  # Classic release build
  - cmake -DCMAKE_BUILD_TYPE=release -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON . $OPENMVG_SOURCE
  # Build for code coverage evaluation
  #- cmake -DOpenMVG_BUILD_COVERAGE=ON -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_EXAMPLES=ON . $OPENMVG_SOURCE

script:
# limit GCC builds to a reduced number of thread for the virtual machine
  - make -j 2
# Perform unit tests only on GCC builds
  - if [ "$CC" = "gcc" ]; then make test; fi

branches:
  only:
    - master

after_success:
  - tar -zcvf lin-binary.tar.gz $OPENMVG_BUILD && md5sum lin-binary.tar.gz > lin-binary.md5

deploy:
  provider: releases
  user: Xeddius
  file:
    - "lin-binary.tar.gz"
    - "lin-binary.md5"
  password:
    secure: "VGDYUwK2ka4PXaAVVLoRbb8dYKarJcpkF3NG/nZwXS2RkbDoXsLr9btNRmejUc09+Y4YsgO8ZaeHh6py3S2YyJUWaZBFpr2I/Ue+mEo63ir396JACUk5sDxHyI47VvEMZYI5swrnPXdPXCWKG4Bl3FJdZnmA9e+SjMoTvu+2q66FbF+DP4zyrBV6Aq/m3fP2gj/9wiD2DkrPag/I4Gb/tI0yEiDaJKNOovDT4bec0DC1jWqxhXWa2EhMId6ocebZS/KYNbGk8Ls8R7K+Ni+cy9cVNte7wwps1f1Oh3948kvkNDce8LTeYznWLqL62LsfryckrqPpW6dhV6zo7g1csKKPh5gdX5j9MKVOzmVYJO4S9yitjzOk1HaiVbtTkXUUIsdNu1+IZK3SsdM0+rF6kgC366rBCsBZkr5VHbwuMrKvkx9hJBUyiyHuNzgW5B9gkSrcF2wd737IC9e0sxfj570AUjrByZvp/ZIOXAqsbTe51Geov4odO27y+XBnR+fU3/EOxzxDFOmez0byOZlUjoq2I609YazuGo7a6e7b/WqDTpZvRYLsbeL2u0knVYyKg0u5DKoK+jH/a5Yg1pG+zSR186PTarq00RP3uraXiFC3FOTsCoXxScx2O9TDi+UnUsjukmiPhpIeLvgr17HV2EG76JgJMfRJxBJfBoeB/So="
  skip_cleanup: true
  on:
    tags: true
